### ISSUE TITLE
Csv  format

### ISSUE THREAD

**Issue by danielstaleiny** [yocode/compare_csvs#1]
Hi, great job on the script. I am trying to tweak it to use `delimeter=";"` and `doublequote=True` but I unable to do that. I am not very skilled in python but if you can point me out to recourse I should use I would be very grateful.

It keeps throwing me error on merge function. 
here is doc but I don't know what to change.
[http://pandas.pydata.org/pandas-docs/stable/merging.html](http://pandas.pydata.org/pandas-docs/stable/merging.html)

I specify correct delimeter and doublequotes base on this
[http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html#pandas.read_csv](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html#pandas.read_csv)

I keep getting this error :(
```
KeyError: 'productid'
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compare_csv.py", line 56, in <module>
    main()
  File "compare_csv.py", line 25, in main
    merge_csvs(file1,file2,column)
  File "compare_csv.py", line 33, in merge_csvs
    merged = a.merge(b, on=column, how='inner')
  File "/usr/lib/python3.6/site-packages/pandas/core/frame.py", line 4607, in merge
    copy=copy, indicator=indicator)
  File "/usr/lib/python3.6/site-packages/pandas/tools/merge.py", line 61, in merge
    copy=copy, indicator=indicator)
  File "/usr/lib/python3.6/site-packages/pandas/tools/merge.py", line 543, in __init__
    self.join_names) = self._get_merge_keys()
  File "/usr/lib/python3.6/site-packages/pandas/tools/merge.py", line 810, in _get_merge_keys
    right_keys.append(right[rk]._values)
  File "/usr/lib/python3.6/site-packages/pandas/core/frame.py", line 2059, in __getitem__
    return self._getitem_column(key)
  File "/usr/lib/python3.6/site-packages/pandas/core/frame.py", line 2066, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/lib/python3.6/site-packages/pandas/core/generic.py", line 1386, in _get_item_cache
    values = self._data.get(item)
  File "/usr/lib/python3.6/site-packages/pandas/core/internals.py", line 3543, in get
    loc = self.items.get_loc(item)
  File "/usr/lib/python3.6/site-packages/pandas/indexes/base.py", line 2136, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 132, in pandas.index.IndexEngine.get_loc (pandas/index.c:4433)
  File "pandas/index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas/index.c:4279)
  File "pandas/src/hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13742)
  File "pandas/src/hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13696)
```

My first line in csv is header containing keys and one of them is `productid`

**Comment by yocode** [comment]
Hey Daniel,

can you send me an example of the two files that you are trying to merge? You don't have to send me anything sensitive just a 10 line example of each file. That way I can customize the script to work for you.

If may be that my README is not clear enough. I want to see the behavior on your two files to see if I need to fix the script. You may have discovered a bug!

Thanks!

Yoni

**Comment by danielstaleiny** [comment]
I found main issue with my first error. When I was deleting some data to test it, I changed structure of csv which resulted to unkown key. 
Now problem is with delimeters. 

1.csv
```
"productid";"name";"price";"currency";"image";"url";"brand"
"11625482-5745495032109116104";"item1";"231,62";"EUR";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"Moschino Kids"
"11734512-8883";"item2";"370,00";"EUR";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"Derek Lam"
"11724546-50";"item3";"372,50";"EUR";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"Coach"
"11468327-5250";"item3";"109,37";"EUR";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"Armani Jeans"
"11724067-77";"item4";"543,51";"EUR";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"En Noir"
"11379536-5248";"item5";"220,93";"EUR";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"Carolina Ritzler"
"11381743-76";"item6";"211,08";"EUR";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"Fengchen Wang"
"11531074-5248";"item7";"EUR";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"Versace"
"11735855-76";"item8";"274,37";"EUR";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"Neil Barrett"
```

2.csv
```
"productid";"name";"price";"currency";"image";"url";"brand"
"11379536-5248";"item5";"220,93";"EUR";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"Caroli"
"11381743-76";"item6";"211,08";"EUR";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"Fengchen Wang"
"11531074-5248";"item7";"454,72";"EUR";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"Versace"
"11735855-76";"item8";"274,37";"EUR";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"Neil Barrett"
"11486287-77";"item9";"114,94";"EUR";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"Fad Three"
"11320933-5152";"item10";"535,00";"EUR";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"Ann Demeulemeester"
"11716551-5254";"item11";"140,26";"EUR";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"Nuur"
"11589203-5254";"item12";"491,40";"EUR";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"Boutique Moschino"
"11686892-5248";"item13";"1182,60";"EUR";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qfV54hVmnzk70XDuq2dKUAEsDh%26pid%3D15.1&f=1";"Rick Owens"
```

After trying again I am getting this one. 
```Traceback (most recent call last):
  File "compare_csv.py", line 56, in <module>
    main()
  File "compare_csv.py", line 26, in main
    diff_csvs(file1,file2)
  File "compare_csv.py", line 38, in diff_csvs
    s = open(file1, 'r', delimeter=';', doublequote=True)
TypeError: 'delimeter' is an invalid keyword argument for this function

```

Which means that I need to change parameters to take my separator. 

It would me nice to take options when running script.  

 **Update** 

After following this error I fix error messages. and run it trough. 
I can see that it is merging two documents together and then create diff. Problem is that it changes characteristics of my csv.  change delimeter to nothing, and change ; to , 

Do you know what parameters I need to pass to function to make it to create delimeter=; and doublequotes. 

Before discovering your script I was thinking about making hash of the items and and compare them instead and removing documents which I found to reduce size of the document to search in. 
Performance is key for me. I can see that your script is O(x+y) which is good enough but if you have any idea how to make it even better I want to hear them :).

Thanks for quick response, I really appreciate that.
